contact_links:
  - name: Join nf-core
    url: https://nf-co.re/join
    about: Please join the nf-core community here
  - name: "Slack #genomeassembler channel"
    url: https://nfcore.slack.com/channels/genomeassembler
    about: Discussion about the nf-core/genomeassembler pipeline
